#markdown: rdiscount
highlighter: rouge
permalink: /:year/:month/:day/:title/
name: "EASTFOTO"
baseurl: "http://www.eastfoto.com"

author: "shuguo"
atom-baseurl: "http://eastfoto.github.com"
disqus: "eastfoto"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive
  - title: Tags
    class: fa fa-tags
    href: /tags
  - title: About
    class: fa fa-user
    href: /about
  - title: Gallery
    class: fa fa-film
    href: http://eastfoto.github.com
  - title: Blogroll
    class: fa fa-link
    href: /links
  - title: Subscribe
    class: fa fa-rss
    href: /atom

